# Случайные числа в NumPy

In [1]:
import numpy as np

In [2]:
# [начало; конец]
np.random.randint(5)

1

In [3]:
np.random.randint(1, 10, 5)

array([6, 2, 3, 6, 8])

In [4]:
np.random.randint(1, 10, (2, 3))

array([[9, 8, 2],
       [2, 8, 3]])

In [6]:
np.random.randint(10, size = (4, 4))

array([[9, 5, 1, 2],
       [6, 9, 4, 7],
       [7, 0, 5, 4],
       [4, 6, 6, 2]])

In [7]:
np.random.choice(2, 5)

array([1, 0, 0, 0, 0])

In [8]:
# Вернуть массив уникальных элементов
np.random.choice(10, 10, replace=False)

array([3, 6, 7, 8, 4, 5, 1, 0, 2, 9])

In [9]:
a = np.arange(10)
np.random.choice(a, size=(2, 4))

array([[9, 6, 3, 4],
       [4, 3, 7, 4]])

In [10]:
weather = ['Солнышко', "Пасмурно", "Дождливо", "Ветрено"]
parm = [0.1, 0.5, 0.3, 0.1]
np.random.choice(weather, size=7, p=parm)

array(['Пасмурно', 'Дождливо', 'Пасмурно', 'Пасмурно', 'Ветрено',
       'Дождливо', 'Пасмурно'], dtype='<U8')

In [11]:
np.random.rand(5)

array([0.63419084, 0.97149388, 0.43934811, 0.79132544, 0.45468399])

In [12]:
np.random.rand(2, 4)

array([[0.62535628, 0.7819938 , 0.02486755, 0.25798589],
       [0.08194875, 0.79475111, 0.93663641, 0.46233553]])

In [13]:
np.random.uniform(1, 10, 5)

array([2.26422364, 7.21338629, 2.5782922 , 4.68519113, 2.91292992])

In [14]:
a = [1, 2, 3, 4, 5]
np.random.shuffle(a)
a

[2, 1, 5, 4, 3]

In [16]:
a = np.arange(10)
np.random.shuffle(a)
a

array([9, 1, 2, 5, 0, 7, 3, 6, 4, 8])

In [19]:
a = np.arange(15).reshape(3, 5)
np.random.shuffle([0])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])