# Линейная алгебра с NumPy

In [5]:
# pip install numpy
import numpy as np

In [6]:
np.__version__

'1.24.1'

## Вектор 

In [7]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [8]:
a.dtype

dtype('int32')

In [9]:
c = np.array([5, 6, 7, 8], dtype=float)
c.dtype

dtype('float64')

In [10]:
a + b

array([15, 23, 14,  8])

In [11]:
a * 2

array([20, 16, 10,  2])

## Матрица

In [13]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
d.shape

(4, 3)

In [16]:
print(f"{d[0,0]=}")
print(f"{d[1,2]=}")
print(f"{d[2,1]=}")

d[0,0]=1
d[1,2]=6
d[2,1]=8


In [17]:
n1 = np.matrix("1,2;3,4;5,6")
n1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [18]:
n2 = np.matrix("-1,-2;9,7;-5,0")
n2

matrix([[-1, -2],
        [ 9,  7],
        [-5,  0]])

In [19]:
n1 + n2

matrix([[ 0,  0],
        [12, 11],
        [ 0,  6]])

In [20]:
n1 * 100

matrix([[100, 200],
        [300, 400],
        [500, 600]])

In [21]:
n1.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [23]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [25]:
# (1)
arr_sum = 0
for i in range(len(arr)):
    arr_sum += arr[i]
print(arr_sum)

10


In [26]:
# (2)
arr_sum = 0
for i in arr:
    arr_sum += i
print(arr_sum)

10


In [27]:
# (3)
arr_sum = np.sum(arr)
print(arr_sum)

10


In [29]:
arr = np.array([1, -2, 3, -4])
print(f"{np.abs(arr) = }")
print(f"{np.sqrt(arr) = }")
print(f"{np.modf(arr) = }")

np.abs(arr) = array([1, 2, 3, 4])
np.sqrt(arr) = array([1.        ,        nan, 1.73205081,        nan])
np.modf(arr) = (array([ 0., -0.,  0., -0.]), array([ 1., -2.,  3., -4.]))


C:\Users\Surflay\AppData\Local\Temp\ipykernel_13764\3644143531.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(f"{np.sqrt(arr) = }")


In [30]:
a = [x for x in range(1, 10)]
b = [x**2 for x in range(1, 10)]
c = [x**3 for x in range(1, 10)]

n = np.array([a,b,c])
n

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  1,   8,  27,  64, 125, 216, 343, 512, 729]])

## Индексы

In [32]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
print(a[1])
print(a[-1])

11
19


In [34]:
a[1] = -1
a

array([10, -1, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
b = a[1:4] # Создаем представление, а не копию
b[1] = -5
print(a)
print(b)

[10 -1 -5 13 14 15 16 17 18 19]
[-1 -5 13]


## Списочная индексация в многомерных массивах

In [40]:
m = np.arange(3 * 3).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
m[[1, 0, -1]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [43]:
indexs = np.array([
    [0, 1],
    [-1, -2]
])

m[indexs]

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [3, 4, 5]]])

In [44]:
m[0] = -1
m

array([[-1, -1, -1],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [45]:
m[1] += 100
m

array([[ -1,  -1,  -1],
       [103, 104, 105],
       [  6,   7,   8]])