# Линейная алгебра с NumPy

In [5]:
# pip install numpy
import numpy as np

In [6]:
np.__version__

'1.24.1'

## Вектор 

In [7]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [8]:
a.dtype

dtype('int32')

In [9]:
c = np.array([5, 6, 7, 8], dtype=float)
c.dtype

dtype('float64')

In [10]:
a + b

array([15, 23, 14,  8])

In [11]:
a * 2

array([20, 16, 10,  2])

## Матрица

In [13]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
d.shape

(4, 3)

In [16]:
print(f"{d[0,0]=}")
print(f"{d[1,2]=}")
print(f"{d[2,1]=}")

d[0,0]=1
d[1,2]=6
d[2,1]=8


In [17]:
n1 = np.matrix("1,2;3,4;5,6")
n1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [18]:
n2 = np.matrix("-1,-2;9,7;-5,0")
n2

matrix([[-1, -2],
        [ 9,  7],
        [-5,  0]])

In [19]:
n1 + n2

matrix([[ 0,  0],
        [12, 11],
        [ 0,  6]])

In [20]:
n1 * 100

matrix([[100, 200],
        [300, 400],
        [500, 600]])

In [21]:
n1.T

matrix([[1, 3, 5],
        [2, 4, 6]])